sudo: required
services: docker
language: minimal
branches:
  only:
  - master
  - /^test-release-*$/
script:
  - DOCKER_CONTENT_TRUST=1 docker build --pull -t "bsycorp/log-forwarder:1.0.$TRAVIS_BUILD_NUMBER" -t "bsycorp/log-forwarder:latest" .
  - docker login -u $DOCKERUSER -p $DOCKERPASS
  - docker push bsycorp/log-forwarder
