name: Build

on:
  push:
    branches:
      - main # Triggers the workflow when commit pushed to master branch
  workflow_dispatch: # Allow manual trigger

jobs:
  release:
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERUSER }}
        password: ${{ secrets.DOCKERPASS }}
    - name: Build and Publish Image
      run: |
        DOCKER_CONTENT_TRUST=1 docker build --pull -t "bsycorp/log-forwarder:1.1.${{github.run_number}}" -t "bsycorp/log-forwarder:latest" .
        docker push bsycorp/log-forwarder:1.1.${{github.run_number}}
        docker push bsycorp/log-forwarder:latest
